// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

namespace Pihrtsoft.Text.RegularExpressions.Linq
{
    internal enum SyntaxKind
    {
        None = 0,
        AnyChar = 1,
        AnyCharExceptLinefeed = 2,
        Assertion = 3,
        BackAssertion = 4,
        BalancingGroup = 5,
        BeginningOfInput = 6,
        BeginningOfInputOrLine = 7,
        Character = 8,
        CharGroup = 9,
        Digit = 10,
        EndOfInput = 11,
        EndOfInputOrBeforeEndingLinefeed = 12,
        EndOfInputOrLine = 13,
        GeneralCategory = 14,
        Group = 15,
        GroupEnd = 16,
        GroupOptions = 17,
        GroupReference = 18,
        IfAssert = 19,
        IfGroup = 20,
        NamedBlock = 21,
        NamedGroup = 22,
        NegativeAssertion = 23,
        NegativeBackAssertion = 24,
        NegativeCharGroup = 25,
        NegativeWordBoundary = 26,
        NonbacktrackingGroup = 27,
        NoncapturingGroup = 28,
        NotDigit = 29,
        NotGeneralCategory = 30,
        NotNamedBlock = 31,
        NotWhiteSpace = 32,
        NotWordChar = 33,
        Options = 34,
        Or = 35,
        PreviousMatchEnd = 36,
        Text = 37,
        WhiteSpace = 38,
        WordBoundary = 39,
        WordChar = 40,
    }
}
