// Copyright (c) Josef Pihrt. All rights reserved. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Globalization;

namespace Pihrtsoft.Text.RegularExpressions.Linq
{
    internal static class TextUtility
    {
        public static string NumberToString(int number)
        {
            if (number >= 0 && number <= 9)
            {
                return _numbers[number];
            }
            else
            {
                return number.ToString(CultureInfo.InvariantCulture);
            }
        }

        public static string GetAsciiCharName(AsciiChar value) => _asciiChars[(int)value];

        private static readonly string[] _numbers = new string[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" };

        private static readonly string[] _asciiChars = new string[] {
            "null",
            "start of heading",
            "start of text",
            "end of text",
            "end of transmission",
            "enquiry",
            "acknowledge",
            "bell",
            "backspace",
            "tab",
            "linefeed",
            "vertical tab",
            "form feed",
            "carriage return",
            "shift out",
            "shift in",
            "data link escape",
            "device control one",
            "device control two",
            "device control three",
            "device control four",
            "negative acknowledge",
            "synchronous idle",
            "end of transmission block",
            "cancel",
            "end of medium",
            "substitute",
            "escape",
            "information separator four",
            "information separator three",
            "information separator two",
            "information separator one",
            "space",
            "exclamation mark",
            "quote mark",
            "number sign",
            "dollar",
            "percent",
            "ampersand",
            "apostrophe",
            "left parenthesis",
            "right parenthesis",
            "asterisk",
            "plus",
            "comma",
            "hyphen",
            "dot",
            "slash",
            "digit zero",
            "digit one",
            "digit two",
            "digit three",
            "digit four",
            "digit five",
            "digit six",
            "digit seven",
            "digit eight",
            "digit nine",
            "colon",
            "semicolon",
            "left angle bracket",
            "equals sign",
            "right angle bracket",
            "question mark",
            "at sign",
            "capital letter a",
            "capital letter b",
            "capital letter c",
            "capital letter d",
            "capital letter e",
            "capital letter f",
            "capital letter g",
            "capital letter h",
            "capital letter i",
            "capital letter j",
            "capital letter k",
            "capital letter l",
            "capital letter m",
            "capital letter n",
            "capital letter o",
            "capital letter p",
            "capital letter q",
            "capital letter r",
            "capital letter s",
            "capital letter t",
            "capital letter u",
            "capital letter v",
            "capital letter w",
            "capital letter x",
            "capital letter y",
            "capital letter z",
            "left square bracket",
            "backslash",
            "right square bracket",
            "circumflex accent",
            "underscore",
            "grave accent",
            "small letter a",
            "small letter b",
            "small letter c",
            "small letter d",
            "small letter e",
            "small letter f",
            "small letter g",
            "small letter h",
            "small letter i",
            "small letter j",
            "small letter k",
            "small letter l",
            "small letter m",
            "small letter n",
            "small letter o",
            "small letter p",
            "small letter q",
            "small letter r",
            "small letter s",
            "small letter t",
            "small letter u",
            "small letter v",
            "small letter w",
            "small letter x",
            "small letter y",
            "small letter z",
            "left curly bracket",
            "vertical bar",
            "right curly bracket",
            "tilde",
            "delete",
        };
    }
}
